# Generated by Django 6.0.3 on 2026-03-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на источник')),
                ('source_text', models.TextField(blank=True, verbose_name='Исходный текст')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('processing', 'Обработка'), ('ready', 'Готов'), ('error', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок модуля')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('key_points', models.JSONField(blank=True, default=list, help_text='Список строк — ключевые мысли модуля', verbose_name='Ключевые тезисы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Флэш-карточка',
                'verbose_name_plural': 'Флэш-карточки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('choices', models.JSONField(default=list, help_text='Список строк — варианты ответа', verbose_name='Варианты ответа')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='Правильный ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_final', models.BooleanField(default=False, help_text='True = вопрос для Final Boss (итогового теста)', verbose_name='Итоговый тест')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Вопрос квиза',
                'verbose_name_plural': 'Вопросы квиза',
                'ordering': ['order'],
            },
        ),
    ]
